from typing import Any

import numpy as np

def play(data: np.ndarray, samplerate: int, blocking: bool = False, loop: bool = False, **kwargs: Any) -> None: ...
def wait() -> None: ...

class OutputStream:
    def __init__(self, samplerate: int, channels: int, dtype: str, **kwargs: Any) -> None: ...
    def __enter__(self) -> OutputStream: ...
    def __exit__(self, *args: Any) -> None: ...
    def write(self, data: np.ndarray) -> bool: ...
