import numpy as np

class Meter:
    rate: float
    block_size: float
    def __init__(self, rate: float, filter_class: str = "K-weighting", block_size: float = 0.400) -> None: ...
    def integrated_loudness(self, data: np.ndarray) -> float: ...
    def loudness_range(self, data: np.ndarray) -> float: ...
